// Generated by Code Assistant Testing Ground
export const dependenciesLog = [
  {
    "package": "PackageName",
    "command": "npm install PackageName",
    "usedIn": "Where its used",
    "reason": "Why its included."
  }
];