// Generated by Code Assistant Testing Ground
export const defaultUserData = {
  "userProfile": {
    "id": 12345,
    "username": "dev_user",
    "email": "developer@example.com",
    "isActive": true,
    "roles": [
      "admin",
      "editor"
    ],
    "preferences": {
      "theme": "dark",
      "notifications": {
        "email": true,
        "push": false,
        "sms": null
      },
      "language": "en-US"
    }
  },
  "sessionData": {
    "loginTimestamp": "2024-01-01T12:00:00.000Z",
    "sessionToken": "abc-123-xyz-789",
    "ipAddress": "192.168.1.1"
  },
  "appData": [
    {
      "module": "dashboard",
      "widgets": [
        {
          "id": "widget-1",
          "type": "chart",
          "config": {
            "chartType": "line",
            "dataPoints": 20
          }
        },
        {
          "id": "widget-2",
          "type": "summary",
          "config": {
            "metric": "revenue"
          }
        }
      ]
    },
    {
      "module": "settings",
      "lastAccessed": "2023-10-27T10:00:00Z"
    }
  ],
  "metadata": {
    "version": "1.2.0",
    "lastUpdated": null,
    "history": []
  }
};