// Generated by Code Assistant Testing Ground
export const commandSet = {
  "version": 1.1,
  "commands": [
    {
      "command": "/checkpoint",
      "description": "Logs the current state of the app to ai_dev/log/checkpoints/checkpoint.ts",
      "usage": "Use after the AI has completed a set of changes to save a backup."
    },
    {
      "command": "/log",
      "description": "Logs the current changes. The AI must analyse the contents of the latest log.ts file in ai_dev/log/update_log/ and update this file with a new entry which includes the current version, a brief description of the edits made, and the original prompt given by the user. If the file becomes large, the AI must create a new file (e.g., update2.ts) and continue appending."
    },
    {
      "command": "/todo",
      "description": "Analyzes the current conversation and remaining work, then updates the `todo.ts` file. New tasks are added to the `tasks` array, and completed tasks are moved to the `completedTasks` array, as per the 'Track Unfinished Tasks' rule."
    }
  ]
};